version: '3.4'

services:
  feed-service:
    image: ${DOCKER_REGISTRY-}feedservice
    build:
      context: ./back-end/feed-service/

  question-service:
    image: ${DOCKER_REGISTRY-}questionservice
    build:
      context: ./back-end/question-service/

  ocelot-gateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: ./back-end/ocelot-gateway/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=7000
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/aspnetapp.pfx
    ports:
      - 7000:443
      - 6000:80
    volumes:
      - ./certs:/app/certs

  front-end:
    image: ${DOCKER_REGISTRY-}front-end
    ports:
      - 3000:3000
    build:
        context: ./front-end/
    volumes:
      - /front-end/usr/src/app
      - /front-end/usr/src/app/node_modules
      - /front-end/usr/src/app/.next

  admin:
    image: ${DOCKER_REGISTRY-}admin
    build:
        context: ./admin/
    ports:
      - "3001:80"

  


