version: '3.4'

services:
  question-service:
    image: ${DOCKER_REGISTRY-}questionservice
    build:
      context: ./back-end/question-service/
    environment:
        - MongoDbConnectionString=${DB1_URL}
        - MongoDbName=question
        - MongoDbQuestionCollectionName=Question
        - MongoDbBookmarkCollectionName=Bookmark
    depends_on:
        - questiondb

  questiondb:
    image: mongo:5.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017

  questiondb-admin:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DB1_URL}
    depends_on:
        - questiondb

  search-service:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: ./back-end/search-service/

  ocelot-gateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: ./back-end/ocelot-gateway/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=7000
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/aspnetapp.pfx
    ports:
      - 7000:443
      - 6000:80
    volumes:
      - ./certs:/app/certs

  admin:
    image: ${DOCKER_REGISTRY-}admin
    build:
        context: ./admin/
    ports:
      - "3001:80"

  profile-service:
    image: ${DOCKER_REGISTRY-}profileservice
    build:
      context: ./back-end/profile-service/
    environment:
        - MongoDbConnectionString=${DB2_URL}
        - MongoDbName=profile
        - MongoDbProfileCollectionName=Profile
    depends_on:
        - profiledb

  profiledb:
    image: mongo:5.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27018:27017

  profiledb-admin:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DB2_URL}
    depends_on:
        - profiledb

  


