# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: basic-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - http:
#       paths:
#         # - path: /answer-service
#         #   pathType: Prefix
#         #   backend:
#         #     service:
#         #       name: answer-service
#         #       port: 
#         #         number: 9092
#         - path: /test
#           pathType: Prefix
#           backend:
#             service:
#               name: question-service
#               port: 
#                 number: 80
#         # - path: /report-service
#         #   pathType: Prefix
#         #   backend:
#         #     service:
#         #       name: report-service
#         #       port: 
#         #         number: 80
#         # - path: /search-service
#         #   pathType: Prefix
#         #   backend:
#         #     service:
#         #       name: search-service
#         #       port: 
#         #         number: 80
#         # - path: /upload-service
#         #   pathType: Prefix
#         #   backend:
#         #     service:
#         #       name: upload-service
#         #       port: 
#         #         number: 80
# Routing file that the Ingress Nginx controller will user
# to determine how to route to our services.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    # gateway
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    # locally set up in hosts file
    - http:
        paths:
          # platform service
          - path: /question-service
            pathType: Prefix
            backend:
              service:
                name: question-service
                port:
                  number: 80