apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    # gateway
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    # locally set up in hosts file
    - http:
        paths:
          # platform service
          - path: /Feed
            pathType: Prefix
            backend:
              service:
                name: question-service
                port:
                  number: 80