apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- answer-service-deployment.yaml
- answer-service-hpa.yml
- profile-service-deployment.yaml
- question-service-deployment.yaml
- report-service-deployment.yaml
- search-service-deployment.yaml
- upload-service-deployment.yaml
- secret.yaml
- basic-ingress.yaml
- rabbitmq-deployment.yaml

namespace: blinddate
images:
- name: answer-service
  newName: seethrough2022/answer-service
  newTag: 7b21adc43af717c6744e148720fbb0e917eb1f82
- name: profile-service
  newName: seethrough2022/profile-service
  newTag: d2476b3843e0b02ec656bbc701d63d587c19a958
- name: question-service
  newName: seethrough2022/question-service
  newTag: a1fcd59b55282e4ad357142eb75426d6f2ce6fe7
- name: report-service
  newName: seethrough2022/report-service
  newTag: 453041a9e08c4db0c59ecd59296733a0324e8289
- name: search-service
  newName: seethrough2022/search-service
  newTag: f6d2a15941ac3bd126a130f452ef67f1476949e6
- name: upload-service
  newName: seethrough2022/upload-service
  newTag: 23921ad1cc9e0382ae3736034f28e340c49ea5d8
