apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- answer-service-deployment.yaml
- profile-service-deployment.yaml
- question-service-deployment.yaml
- report-service-deployment.yaml
- search-service-deployment.yaml
- upload-service-deployment.yaml
- secret.yaml
- basic-ingress.yaml
- rabbitmq-deployment.yaml

namespace: blinddate
images:
- name: answer-service
  newName: seethrough2022/answer-service
  newTag: 47dd5ab99cedff9519874fa94247abfdff93d896
- name: profile-service
  newName: seethrough2022/profileservice
  newTag: latest
- name: question-service
  newName: seethrough2022/questionservice
  newTag: latest
- name: report-service
  newName: seethrough2022/reportservice
  newTag: latest
- name: search-service
  newName: seethrough2022/searchservice
  newTag: latest
- name: upload-service
  newName: seethrough2022/uploadservice
  newTag: latest
