apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- answer-service-deployment.yaml
- answer-service-hpa.yml
- profile-service-deployment.yaml
- question-service-deployment.yaml
- report-service-deployment.yaml
- search-service-deployment.yaml
- upload-service-deployment.yaml
- secret.yaml
- basic-ingress.yaml
- rabbitmq-deployment.yaml

namespace: blinddate
images:
- name: answer-service
  newName: seethrough2022/answer-service
  newTag: 7c6daefb39f2cad296b04df07457783a096dc420
- name: profile-service
  newName: seethrough2022/profile-service
  newTag: 4d9decb78d1280edfad32f0883968dbd0da2346c
- name: question-service
  newName: seethrough2022/question-service
  newTag: 51681992bd43f134ce6981d54c3fc16e7c04ba9b
- name: report-service
  newName: seethrough2022/report-service
  newTag: 5a7ae0949bfa2ac2d759ba74f2a8a2872f663cf2
- name: search-service
  newName: seethrough2022/search-service
  newTag: f6d2a15941ac3bd126a130f452ef67f1476949e6
- name: upload-service
  newName: seethrough2022/upload-service
  newTag: 23921ad1cc9e0382ae3736034f28e340c49ea5d8
