apiVersion: apps/v1
kind: Deployment

metadata:
  name: question-deployment
  labels:
    app: question

spec:
  replicas: 2

  selector:
    matchLabels:
      app: question

  template:
    metadata:
      labels:
        app: question

    spec:
      containers:
      - name: question
        image: seethrough2022/questionservice:latest

        ports:
          - containerPort: 80

        env:
          - name: MongoDbSettings__ConnectionString
            value: XXX

          - name: MongoDbSettings__DatabaseName
            value: XXX

          - name: Auth0Settings__Authority
            value: XXX
          
          - name: Auth0Settings__Audience
            value: XXX

---
apiVersion: v1
kind: Service

metadata:
  name: question-service

spec:

  selector:
    app: question

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80