# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose convert -o ./k8s
#     kompose.version: 1.26.1 (HEAD)
#   labels:
#     io.kompose.service: question-service
#   name: question-service
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: question-service
#   strategy: {}
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose convert -o ./k8s
#         kompose.version: 1.26.1 (HEAD)
#       labels:
#         io.kompose.service: question-service
#     spec:
#       containers:
#         - env:
#             - name: Auth0Settings__Audience
#             - name: Auth0Settings__Authority
#             - name: MongoDbSettings__ConnectionString
#             - name: MongoDbSettings__DatabaseName
#               value: QuestionDB
#           image: seethrough2022/questionservice:1.0.0
#           imagePullPolicy: Always
#           name: question-service
#           resources: {}
#       restartPolicy: Always
# status: {}

kind: Pod
apiVersion: v1
metadata:
  name: question-app
  labels:
    app: question
spec:
  containers:
    - env:
        - name: Auth0Settings__Audience
        - name: Auth0Settings__Authority
        - name: MongoDbSettings__ConnectionString
        - name: MongoDbSettings__DatabaseName
          value: QuestionDB
      image: seethrough2022/questionservice:latest
      imagePullPolicy: Always
      name: question-app
      ports:
        - containerPort: 80
      resources: {}
  restartPolicy: Always


---

kind: Service
apiVersion: v1
metadata:
  name: question-service
spec:
  type: NodePort
  selector:
    app: question
  ports:
      # Port accessible inside cluster
      - port: 80
      # Port to forward to inside the pod
        targetPort: 80