spring:
  data:
    mongodb:
      uri: ${env.DB_URL_ANSWER}
  rabbitmq:
    addresses: ${env.RabbitMQ_URI}
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${env.AUTH0_AUTHORITY}
server:
  port: 9092
auth0:
  audience: ${env.AUTH0_AUDIENCE}
.env:
  directory: "../../"
  filename: ".env"