# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Front-end Node.js CI

on:
  pull_request:     
    branches: 
      - main
    paths:
      - front-end/**

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
      working-directory: front-end
    - name: Build
      run: npm run build
      working-directory: front-end
       
    # - name: Test
    #   run: npm test
    #   working-directory: smitenoobleague-web-app