name: Docker Build And Push

on:
  pull_request:     
    branches: 
      - main
    paths:
      - back-end/**      
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: '${{ secrets.DOCKER_USER }}'
          DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build ocelotgateway
        run: |
          cd back-end/ocelot-gateway
          docker build . -t seethrough2022/ocelotgateway:1.0.0
      - name: docker push
        run: |
          docker push seethrough2022/ocelotgateway:1.0.0
